/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace InvoiceRegistry {
  export type InvoiceStruct = {
    creator: AddressLike;
    payer: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    dueDate: BigNumberish;
    status: BigNumberish;
  };

  export type InvoiceStructOutput = [
    creator: string,
    payer: string,
    token: string,
    amount: bigint,
    dueDate: bigint,
    status: bigint
  ] & {
    creator: string;
    payer: string;
    token: string;
    amount: bigint;
    dueDate: bigint;
    status: bigint;
  };
}

export interface InvoiceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancel"
      | "createInvoice"
      | "getInvoice"
      | "invoices"
      | "nextInvoiceId"
      | "pay"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InvoiceCancelled"
      | "InvoiceCreated"
      | "InvoicePaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createInvoice",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invoices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextInvoiceId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pay", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getInvoice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "invoices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextInvoiceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
}

export namespace InvoiceCancelledEvent {
  export type InputTuple = [invoiceId: BigNumberish, creator: AddressLike];
  export type OutputTuple = [invoiceId: bigint, creator: string];
  export interface OutputObject {
    invoiceId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceCreatedEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    creator: AddressLike,
    payer: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    dueDate: BigNumberish
  ];
  export type OutputTuple = [
    invoiceId: bigint,
    creator: string,
    payer: string,
    token: string,
    amount: bigint,
    dueDate: bigint
  ];
  export interface OutputObject {
    invoiceId: bigint;
    creator: string;
    payer: string;
    token: string;
    amount: bigint;
    dueDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoicePaidEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    payer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [invoiceId: bigint, payer: string, amount: bigint];
  export interface OutputObject {
    invoiceId: bigint;
    payer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InvoiceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): InvoiceRegistry;
  waitForDeployment(): Promise<this>;

  interface: InvoiceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancel: TypedContractMethod<[invoiceId: BigNumberish], [void], "nonpayable">;

  createInvoice: TypedContractMethod<
    [
      payer: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      dueDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getInvoice: TypedContractMethod<
    [invoiceId: BigNumberish],
    [InvoiceRegistry.InvoiceStructOutput],
    "view"
  >;

  invoices: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint] & {
        creator: string;
        payer: string;
        token: string;
        amount: bigint;
        dueDate: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  nextInvoiceId: TypedContractMethod<[], [bigint], "view">;

  pay: TypedContractMethod<[invoiceId: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[invoiceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createInvoice"
  ): TypedContractMethod<
    [
      payer: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      dueDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getInvoice"
  ): TypedContractMethod<
    [invoiceId: BigNumberish],
    [InvoiceRegistry.InvoiceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "invoices"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint] & {
        creator: string;
        payer: string;
        token: string;
        amount: bigint;
        dueDate: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextInvoiceId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<[invoiceId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "InvoiceCancelled"
  ): TypedContractEvent<
    InvoiceCancelledEvent.InputTuple,
    InvoiceCancelledEvent.OutputTuple,
    InvoiceCancelledEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceCreated"
  ): TypedContractEvent<
    InvoiceCreatedEvent.InputTuple,
    InvoiceCreatedEvent.OutputTuple,
    InvoiceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InvoicePaid"
  ): TypedContractEvent<
    InvoicePaidEvent.InputTuple,
    InvoicePaidEvent.OutputTuple,
    InvoicePaidEvent.OutputObject
  >;

  filters: {
    "InvoiceCancelled(uint256,address)": TypedContractEvent<
      InvoiceCancelledEvent.InputTuple,
      InvoiceCancelledEvent.OutputTuple,
      InvoiceCancelledEvent.OutputObject
    >;
    InvoiceCancelled: TypedContractEvent<
      InvoiceCancelledEvent.InputTuple,
      InvoiceCancelledEvent.OutputTuple,
      InvoiceCancelledEvent.OutputObject
    >;

    "InvoiceCreated(uint256,address,address,address,uint256,uint256)": TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;
    InvoiceCreated: TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;

    "InvoicePaid(uint256,address,uint256)": TypedContractEvent<
      InvoicePaidEvent.InputTuple,
      InvoicePaidEvent.OutputTuple,
      InvoicePaidEvent.OutputObject
    >;
    InvoicePaid: TypedContractEvent<
      InvoicePaidEvent.InputTuple,
      InvoicePaidEvent.OutputTuple,
      InvoicePaidEvent.OutputObject
    >;
  };
}
